### ISSUE TITLE
OpenSSL API Compatibility Layer

### ISSUE THREAD

**Issue by SimonTate** [rustls/rustls-openssl-compat#4]
**Checklist**
* [x] I've searched the issue tracker for similar requests

**Is your feature request related to a problem? Please describe.**

Use rustls as a drop in replacement for OpenSSL with the public API from OpenSSL 3.2.0 (or latest stable 3.x version) as per the roadmap (https://github.com/rustls/rustls/blob/main/ROADMAP.md) so that I can use rustls as my main TLS implementation with applications that are not written in rust and depend on openssl.

**Describe the solution you'd like**

libssl.so implemented by rustls with the same header file names and functions as openssl. Allow a `main.c` to be linked with original openssl libs or rustls libs and functionally work the same way. Initially starting by implementing enough to run openssl-bench and then enough to use in curl, and then the whole public API.

**Describe alternatives you've considered**

Convert everyone to using rust 🦀  or could create a separate C library that is NOT a drop in replacement. I think both of these would harm adoption rates though.

**Additional context**

This is part of the roadmap. I'm just creating this for initial discussion on plans to implement before there is a PR opened. Apologies if work has already started on this.

**Comment by cpu** [comment]
> cpu transferred this issue from rustls/rustls now

The compat repository is now public, so I've moved this issue over here.

**Comment by cpu** [comment]
I forgot to circle back to this issue when the first version of the compat layer was released: https://www.memorysafety.org/blog/rustls-nginx-compatibility-layer/

I'm going to close this ticket for now as we've implemented sufficient API surface for `curl` and `nginx` on Ubuntu 22.04/24.04 within our described limitations/caveats.

We're certainly open to looking at other required pieces of API surface in order to support other applications but I think it will be best to discuss this in new issues that have a narrower scope. 

Thanks everyone!
